name: Deploy FTP Dosea

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      work-directory: Codigo/Gerefrota

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/checkout@v1
        with:
          dotnet-version: '5.0'

      - name: Restauração de dependências
        run: |
          cd ${{env.work-directory}}
          dotnet restore

      - name: Buildando Aplicação
        run: |
          cd ${{env.work-directory}}
          dotnet build --no-restore

      - name: Fazendo release da Aplicação
        run: |
          cd ${{env.work-directory}}
          dotnet build --configuration Release --no-restore

      - name: Testando Aplicação
        run: |
          cd ${{env.work-directory}}
          dotnet test --no-build --verbosity normal

      - name: Publicando Aplicação
        run: |
          cd ${{env.work-directory}}
          dotnet publish -c Release -o '${{ github.workspace }}/out'

#       - name: Zipando Arquivos
#         run: |
#           cd ${{ github.workspace }}/out
#           zip -r ${{ github.workspace }}/out.zip *
          
      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
#           server: win8038.site4now.net
#           username: gerefrota-gab
#           password: salas@2022
#           local-dir: publish/
          local-dir: ${{ github.workspace }}/out/
          remote-dir: ./
          exclude: |
            */.git
            */.git/**

#       - name: Deploy para AWS
#         uses: einaregilsson/beanstalk-deploy@v20
#         with:
#           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           application_name: gerefrota
#           environment_name: Gerefrota-env
#           version_label: ${{ github.run_id }}
#           version_description: ${{ github.sha }}
#           region: ${{ secrets.AWS_REGION }}
#           deployment_package: ${{ github.workspace }}/out.zip
#           use_existing_version_if_available: true
